"""Interactive SSL setup for Docker (Nginx + Social-Hunt + IOPaint)."""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Optional

ROOT = Path(__file__).resolve().parent
SSL_DIR = ROOT / "ssl"
TEMPLATE_CONF = SSL_DIR / "nginx-ssl.conf.template"
OUTPUT_CONF = SSL_DIR / "nginx-ssl.conf"
ENV_TEMPLATE = SSL_DIR / "ssl.env.template"
ENV_OUTPUT = SSL_DIR / "ssl.env"


def prompt(text: str, default: Optional[str] = None, required: bool = False) -> str:
    while True:
        suffix = f" [{default}]" if default else ""
        value = input(f"{text}{suffix}: ").strip()
        if not value and default is not None:
            value = default
        if required and not value:
            print("Value required.")
            continue
        return value


def prompt_yes_no(text: str, default: bool = True) -> bool:
    hint = "[Y/n]" if default else "[y/N]"
    while True:
        value = input(f"{text} {hint}: ").strip().lower()
        if not value:
            return default
        if value in ("y", "yes"):
            return True
        if value in ("n", "no"):
            return False
        print("Enter y or n.")


def render_template(template: str, replacements: dict[str, str]) -> str:
    output = template
    for key, value in replacements.items():
        output = output.replace(f"{{{{{key}}}}}", value)
    return output


def main() -> int:
    print("Social-Hunt Docker SSL setup (Nginx)")
    print("This will generate docker/ssl/nginx-ssl.conf and docker/ssl/ssl.env")
    print()

    SSL_DIR.mkdir(parents=True, exist_ok=True)
    (SSL_DIR / "certbot" / "www").mkdir(parents=True, exist_ok=True)
    (SSL_DIR / "certbot" / "conf").mkdir(parents=True, exist_ok=True)
    (SSL_DIR / "certs").mkdir(parents=True, exist_ok=True)

    if not TEMPLATE_CONF.exists():
        print(f"Template not found: {TEMPLATE_CONF}")
        return 1

    domain = prompt("Domain name (FQDN)", required=True)
    use_lets_encrypt = prompt_yes_no("Use Let's Encrypt", default=True)

    if use_lets_encrypt:
        email = prompt("Email for Let's Encrypt", required=True)
        ssl_cert_path = f"/etc/letsencrypt/live/{domain}/fullchain.pem"
        ssl_key_path = f"/etc/letsencrypt/live/{domain}/privkey.pem"
    else:
        email = ""
        cert_file = prompt(
            "Certificate filename under docker/ssl/certs",
            default="fullchain.pem",
            required=True,
        )
        key_file = prompt(
            "Private key filename under docker/ssl/certs",
            default="privkey.pem",
            required=True,
        )
        ssl_cert_path = f"/etc/ssl/custom/{cert_file}"
        ssl_key_path = f"/etc/ssl/custom/{key_file}"

    template_text = TEMPLATE_CONF.read_text(encoding="utf-8")
    rendered = render_template(
        template_text,
        {
            "SERVER_NAME": domain,
            "SSL_CERT_PATH": ssl_cert_path,
            "SSL_KEY_PATH": ssl_key_path,
        },
    )
    OUTPUT_CONF.write_text(rendered, encoding="utf-8")

    if ENV_TEMPLATE.exists():
        env_template_text = ENV_TEMPLATE.read_text(encoding="utf-8")
        env_rendered = render_template(
            env_template_text,
            {
                "SSL_DOMAIN": domain,
                "CERTBOT_EMAIL": email,
            },
        )
        ENV_OUTPUT.write_text(env_rendered.strip() + "\n", encoding="utf-8")
    else:
        env_lines = [
            "# Generated by docker/setup_ssl.py",
            f"SSL_DOMAIN={domain}",
            f"CERTBOT_EMAIL={email}",
            "",
        ]
        ENV_OUTPUT.write_text("\n".join(env_lines), encoding="utf-8")

    print()
    print("Generated:")
    print(f"- {OUTPUT_CONF}")
    print(f"- {ENV_OUTPUT}")

    print()
    if use_lets_encrypt:
        print("Next steps (Let's Encrypt):")
        print("1) From the docker/ folder, issue the cert (uses port 80):")
        print("   docker compose --profile certbot run --rm --service-ports certbot")
        print("2) Start the stack:")
        print("   docker compose --profile ssl up -d")
        print("3) Renew later (while nginx is running):")
        print(
            "   docker compose --profile certbot run --rm certbot renew --webroot -w /var/www/certbot"
        )
    else:
        print("Next steps (custom cert):")
        print("1) Copy your cert/key into docker/ssl/certs")
        print("2) Start the stack:")
        print("   docker compose --profile ssl up -d")

    return 0


if __name__ == "__main__":
    sys.exit(main())
